In [3]:
import csv
with open("data.csv","w",newline="") as file:
    writer=csv.writer(file)
    writer.writerow(["Name","Age","City"])
    writer.writerow(["Pavan","25","Vijayawada"])
    writer.writerow(["mani","23","Hyderabad"])

In [4]:
import csv
with open("data.csv","r") as file:
    reader=csv.reader(file)
    for row in reader:
        print(row)

['Name', 'Age', 'City']
['Pavan', '25', 'Vijayawada']
['mani', '23', 'Hyderabad']


Libraries

In [5]:
import numpy as np

In [6]:
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
l=range(1000)
%timeit [i**2 for i in l]

297 μs ± 22.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [14]:
a=np.arange(1000)
%timeit a**2

4.57 μs ± 371 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Creating arrays

In [23]:
a=np.array([1,2,3,4]) #one dimensional array or vectors

In [16]:
print(a.ndim)

1


In [24]:
b=np.array([[1,2,3],[4,5,5]]) #two dimensional array or matrix
print(b)

[[1 2 3]
 [4 5 5]]


In [18]:
print(b.ndim)

2


In [21]:
c=np.array([[[1,2],[3,4]],[[4,5],[6,7]]]) #3 dimensional (in cube)
print(c)
print(c.ndim)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]
3


In [22]:
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 3)
(2, 2, 2)


# Functions for creating array

In [25]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [28]:
#using linspace
a=np.linspace(0,1,4)
print(a)

[0.         0.33333333 0.66666667 1.        ]


In [29]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [33]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [34]:
print(np.diag(a))

[1 2 3 4]


# Basic Data types

In [35]:
a=np.arange(10)
print(a.dtype)

int64


In [36]:
a=np.arange(10,dtype="float")
print(a.dtype)

float64


In [37]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


# Other data types

In [38]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [39]:
a=np.array([True,False])
print(a.dtype)

bool


In [43]:
a=np.array(["aditya degree college"])
print(a.dtype) #unicode string type

<U21


# Indexing and slicing

In [44]:
a=np.arange(10)
print(a[5])

5


In [45]:
a=np.diag([1,2,3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [48]:
print(a[0,0])

1


In [49]:
b=np.arange(1,10)
print(b[2:5])

[3 4 5]


# slicing

In [2]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(a[1:8:3])

[1 4 7]


In [9]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [10]:
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [11]:
a[1,1]=5
print(a)

[[1 0 0]
 [0 5 0]
 [0 0 3]]


In [13]:
a=np.arange(10)
a[4:]=9
a

array([0, 1, 2, 3, 9, 9, 9, 9, 9, 9])

# copying and viewing

In [14]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [15]:
print(np.shares_memory(a,b))

True


In [16]:
b[0]=10
print(b)
print(a)

[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [17]:
a=np.arange(10)
b=a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [18]:
print(np.shares_memory(a,b))

False


In [24]:
print(b.base)

None


# random number generator

In [28]:
import numpy as np
a=np.random.randint(0,20,15)
print(a)

[ 3  7 14 19 13  2  2 16 15  0  3  1 13 11  3]


In [31]:
mask=(a%2==0)
new_a=a[mask]
print(new_a)


[14  2  2 16  0]


In [32]:
a[mask]=-1
print(a)

[ 3  7 -1 19 13 -1 -1 -1 15 -1  3  1 13 11  3]


# Element wise operation

# 1. Basic operation

In [33]:
a=np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [34]:
print(a**2)

[ 1  4  9 16]


# All arithmetic operates element wise

In [35]:
b=np.ones(4) +1
print("a=",a)
print("b=",b)

a= [1 2 3 4]
b= [2. 2. 2. 2.]


In [36]:
print(a*b)

[2. 4. 6. 8.]


In [37]:
c=np.diag([1,2,3,4])
print(c)
print(c *c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [38]:
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


# Comparision operator

In [40]:
a=np.array([1,2,6])
b=np.array([4,5,6])
print(a==b)

[False False  True]


In [41]:
print(a<b)

[ True  True False]


In [42]:
print(a>b)

[False False False]


In [47]:
# array wise comparision
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])
print(np.array_equal(a,c))

True


# Logical operator

In [48]:
a=np.array([1,0,1,0],dtype="bool")
b=np.array([1,1,0,0],dtype="bool")
print(np.logical_or(a,b))

[ True  True  True False]


In [49]:
print(np.logical_and(a,b))

[ True False False False]


In [50]:
print(np.logical_not(a))

[False  True False  True]


# Trigonometry/Transcendental Functions

In [51]:
a=np.arange(4)
print(a)

[0 1 2 3]


In [52]:
print(np.sin(a))

[0.         0.84147098 0.90929743 0.14112001]


In [53]:
np.log(a)

C:\Users\DELL\AppData\Local\Temp\ipykernel_2516\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229])